// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOtp = "otp"

// Otp mapped from table <otp>
type Otp struct {
	IDOtp          int32     `gorm:"column:idOtp;primaryKey;autoIncrement:true" json:"idOtp"`
	OtpExpire      time.Time `gorm:"column:otp_expire;not null" json:"otp_expire"`
	ActivationCode string    `gorm:"column:activation_code;not null" json:"activation_code"`
	Email          string    `gorm:"column:email;not null" json:"email"`
	OtpSecret      string    `gorm:"column:otp_secret;not null" json:"otp_secret"`
}

// TableName Otp's table name
func (*Otp) TableName() string {
	return TableNameOtp
}
