// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePasswordResetToken = "password_reset_tokens"

// PasswordResetToken mapped from table <password_reset_tokens>
type PasswordResetToken struct {
	IdpasswordResetTokens int32     `gorm:"column:idpassword_reset_tokens;primaryKey;autoIncrement:true" json:"idpassword_reset_tokens"`
	UserID                int32     `gorm:"column:user_id;not null" json:"user_id"`
	Expire                time.Time `gorm:"column:expire;not null" json:"expire"`
	PwdToken              string    `gorm:"column:pwd_token;not null" json:"pwd_token"`
}

// TableName PasswordResetToken's table name
func (*PasswordResetToken) TableName() string {
	return TableNamePasswordResetToken
}
